# Makefile
# For ui library.

#
# Options.
#
# Directory.
SRC_DIR = $(WORK_DIR)/src
OBJ_DIR = $(TMP_DIR)/main
# Search.
INCLUDE_DIR = -I$(SCI_DIR) -I$(ATR_DIR) -I$(EARTH_DIR) -I$(HUB_H_DIR)

#
# Include.
#
OPT_LST = ../../opt.lst
include $(OPT_LST)

default: bin_file

clean: clean_obj
